// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrMJjPbHnTvDAr1hD-RZjyRQWJ0pnsRLM',
    appId: '1:743256134588:web:f014c48be075dd1c0e91b9',
    messagingSenderId: '743256134588',
    projectId: 'gestao-escola-b6b96',
    authDomain: 'gestao-escola-b6b96.firebaseapp.com',
    storageBucket: 'gestao-escola-b6b96.firebasestorage.app',
    measurementId: 'G-S1701JWWS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS7gJF5aw6Md-LcXAJZk1mLwV_T4FZUNI',
    appId: '1:743256134588:android:95dc8d6d3d34b2ed0e91b9',
    messagingSenderId: '743256134588',
    projectId: 'gestao-escola-b6b96',
    storageBucket: 'gestao-escola-b6b96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj8GGNftval0D7qGgF37SmjVJTPJYhODE',
    appId: '1:743256134588:ios:18ff88b5a844eff50e91b9',
    messagingSenderId: '743256134588',
    projectId: 'gestao-escola-b6b96',
    storageBucket: 'gestao-escola-b6b96.firebasestorage.app',
    iosBundleId: 'com.example.gestaoEscolar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj8GGNftval0D7qGgF37SmjVJTPJYhODE',
    appId: '1:743256134588:ios:18ff88b5a844eff50e91b9',
    messagingSenderId: '743256134588',
    projectId: 'gestao-escola-b6b96',
    storageBucket: 'gestao-escola-b6b96.firebasestorage.app',
    iosBundleId: 'com.example.gestaoEscolar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrMJjPbHnTvDAr1hD-RZjyRQWJ0pnsRLM',
    appId: '1:743256134588:web:1cd36660f5b605810e91b9',
    messagingSenderId: '743256134588',
    projectId: 'gestao-escola-b6b96',
    authDomain: 'gestao-escola-b6b96.firebaseapp.com',
    storageBucket: 'gestao-escola-b6b96.firebasestorage.app',
    measurementId: 'G-6QFDCCM8R1',
  );
}
